Use customer_behavior;
select * from customer;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender ; 

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    discount_applied,
    purchase_amount
FROM customer
WHERE purchase_amount >
(
    SELECT AVG(purchase_amount)
    FROM customer
    WHERE discount_applied = 'YES'
);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT * from 
(
	SELECT item_purchased AS products, round(AVG(review_rating) ,2) AS AVG_review,
	   DENSE_RANK() OVER (ORDER BY AVG(review_rating) desc ) AS ranking   
	from customer
	GROUP BY  item_purchased
)t
where ranking <= 5 ;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT * FROM
(
	SELECT shipping_type ,ROUND(AVG(purchase_amount),2) AS AVG_purchasing 
	FROM customer
	GROUP BY shipping_type 
)t
WHERE shipping_type IN ("Express" , "Standard") ;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status ,COUNT(customer_id) AS total_customer , 
ROUND(AVG(purchase_amount),2) AS AVG_spend ,SUM(purchase_amount) AS total_revenue
FROM CUSTOMER 
GROUP BY subscription_status ;

-- NO , subscribed customers are not spending  more.

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,COUNT(*) AS total_puchase,
SUM( CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END ) AS discount_purcase,
CONCAT(COALESCE(ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)*100.0/NULLIF(COUNT(*),0),2),0) ,"%") AS discounted_purchase
FROM customer 
GROUP BY item_purchased 
ORDER BY discounted_purchase DESC
LIMIT 5 ;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
 SELECT customer_id,previous_purchases,
 CASE 
	 WHEN previous_purchases=1 THEN "New"
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
	 ELSE "Loyalty"
 END    AS customer_segment 
 FROM customer
)
SELECT customer_segment ,COUNT(*) AS "No. of customer"
FROM customer_type 
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS 
(
 SELECT category,item_purchased ,
 COUNT(customer_id) AS total_orders ,
 ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS product_ranking 
 FROM customer 
 GROUP BY category,item_purchased
)
SELECT product_ranking,category,item_purchased,total_orders
FROM product_counts
WHERE product_ranking <=3 ; 


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status ,
COUNT(customer_id) AS repeat_buyers 
FROM CUSTOMER 
WHERE previous_purchases > 5 
GROUP BY subscription_status ;


-- Q10. What is the revenue contribution of each age group?

SELECT Age_groups , SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY Age_groups 
ORDER BY total_revenue DESC ; 